name: Build and test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container: osrf/ros:galactic-desktop

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install pip
        run: |
          apt-get -y update
          apt-get -y install python3-pip

      - name: Search packages in this repository
        id: list_packages
        run: |
          echo ::set-output name=package_list::$(colcon list --names-only)

      - name: Show target packages
        run: |
          echo "Target packages: ${{ steps.list_packages.outputs.package_list }}"

      - name: Set git config for private repositories
        run: |
          git config --local --unset-all http.https://github.com/.extraheader || true
          git config --global url.https://${{ secrets.REPO_TOKEN }}@github.com.insteadOf 'https://github.com'

      - name: Clone dependency packages
        run: |
          mkdir dependency_ws
          vcs import dependency_ws < build_depends.repos

      - name: Remove irrelevant packages
        run: |
          mkdir necessary_packages_ws

          necessary_packages=$(colcon list --packages-up-to ${{ steps.list_packages.outputs.package_list }} | awk '{ print $2 }')
          for necessary_package in ${necessary_packages}; do
            mv "$necessary_package" necessary_packages_ws
          done

          rm -rf dependency_ws

      - name: Install dependencies
        run: |
          apt-get -y update
          rosdep update
          rosdep install -y --from-paths . --ignore-src --rosdistro galactic

      - name: Build
        run: |
          . /opt/ros/galactic/setup.sh
          colcon build --event-handlers console_cohesion+ \
            --packages-up-to ${{ steps.list_packages.outputs.package_list }} \
            --cmake-args -DCMAKE_BUILD_TYPE=Release

      - name: Run tests
        run: |
          . /opt/ros/galactic/setup.sh
          colcon test --event-handlers console_cohesion+ \
            --packages-select ${{ steps.list_packages.outputs.package_list }} \
            --return-code-on-test-failure
